# Generated by Django 3.1.7 on 2021-06-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newImg', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('newCate', models.TextField(blank=True, null=True)),
                ('newTitle', models.TextField(blank=True, null=True)),
                ('newContent', models.TextField(blank=True, null=True)),
                ('newView', models.IntegerField(default=0)),
                ('newTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
