# Generated by Django 3.1.7 on 2021-06-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userInfo', models.JSONField(null=True)),
                ('chatName', models.TextField(blank=True, null=True)),
                ('chatEmail', models.TextField(blank=True, null=True)),
                ('chatContent', models.JSONField(null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('sessionId', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
