# Generated by Django 3.1.7 on 2021-06-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderAvatar', models.TextField(blank=True, null=True)),
                ('orderName', models.TextField(blank=True, null=True)),
                ('orderEmail', models.TextField(blank=True, null=True)),
                ('orderPhone', models.TextField(blank=True, null=True)),
                ('orderAddress', models.TextField(blank=True, null=True)),
                ('orderTinh', models.TextField(blank=True, null=True)),
                ('orderHuyen', models.TextField(blank=True, null=True)),
                ('orderList', models.TextField(blank=True, null=True)),
                ('orderTotal', models.IntegerField(default=0)),
                ('orderPaymentMethod', models.TextField(blank=True, null=True)),
                ('orderDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
