# Generated by Django 3.1.7 on 2021-06-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderList',
            field=models.JSONField(null=True),
        ),
    ]
