# Generated by Django 3.1.7 on 2021-06-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateName', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.TextField(blank=True, null=True)),
                ('productSale', models.IntegerField(default=0)),
                ('productSold', models.IntegerField(default=0)),
                ('productDate', models.DateTimeField(auto_now=True)),
                ('productPrice', models.IntegerField(default=0)),
                ('productCate', models.TextField(blank=True, null=True)),
                ('productColor', models.JSONField(null=True)),
                ('productDes', models.TextField(blank=True, null=True)),
                ('productVote', models.IntegerField(default=0)),
                ('productFeature', models.JSONField(null=True)),
                ('productImg', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
