# Generated by Django 3.1.7 on 2021-06-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productVote',
            field=models.JSONField(null=True),
        ),
    ]
